// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjy7Cqo-DZNu5D1YxirQxafSNqf5hvgi4',
    appId: '1:71592851438:web:7d2987b445533530d980ff',
    messagingSenderId: '71592851438',
    projectId: 'newproject-5edbf',
    authDomain: 'newproject-5edbf.firebaseapp.com',
    storageBucket: 'newproject-5edbf.appspot.com',
    measurementId: 'G-BWG9BP054D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCegkJXE1B33hOqKwWu3oDbrT6D3D-owIc',
    appId: '1:71592851438:android:85a6eedaab16a3ced980ff',
    messagingSenderId: '71592851438',
    projectId: 'newproject-5edbf',
    storageBucket: 'newproject-5edbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB97uffWFF5Wfn8Bqr45PXEBrBENU4fmlc',
    appId: '1:71592851438:ios:677000ecb198fbc1d980ff',
    messagingSenderId: '71592851438',
    projectId: 'newproject-5edbf',
    storageBucket: 'newproject-5edbf.appspot.com',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB97uffWFF5Wfn8Bqr45PXEBrBENU4fmlc',
    appId: '1:71592851438:ios:677000ecb198fbc1d980ff',
    messagingSenderId: '71592851438',
    projectId: 'newproject-5edbf',
    storageBucket: 'newproject-5edbf.appspot.com',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjy7Cqo-DZNu5D1YxirQxafSNqf5hvgi4',
    appId: '1:71592851438:web:aec24d0b2c3cffb7d980ff',
    messagingSenderId: '71592851438',
    projectId: 'newproject-5edbf',
    authDomain: 'newproject-5edbf.firebaseapp.com',
    storageBucket: 'newproject-5edbf.appspot.com',
    measurementId: 'G-VW6K14EQSS',
  );
}
